# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb05ed762f48d4ff9b71b8c2cf39fd60f431a7a0f0db7b9d54f7f4317c5d7809ec476d6f8744f1af3d93a101bda12fc53532043e726e18b8b704700c646b1478

test:
  secret_key_base: 272d23eb9e541494ed028864288a8838b40c719c2ca46f0f17e44c9e0c99cee563e4004a8310960b99480ef91157ec326a757338ff040c9269dc9cb43ed6f5cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
